add 'in' condition for table filter
beekeeper-studio/beekeeper-studio pull request #1098
Opened 2022-03-08 10:30 UTC by yogski

## Pull Request for #884 

### Changes
- Added `IN` option for filtering table
- Changed placeholder a little bit for easier UX

### Notes
I took a bit from raw filtering option and put it as new option.
`IN` should be able to handle multiple values. It is different than other options (equal, less than, like, etc.), so I returned it as string like in raw filter instead of arrays. Added parentheses for wrapping.

### Demo
![new-in-filter](https://user-images.githubusercontent.com/29651147/157216972-ddf635ea-fdb2-432d-9a7e-21b62eb42e13.gif)

2022-03-11 20:42 UTC, rathboma commented
Thanks! This looks awesome.

I think thee are a couple of minor things that need changing:

Looks like for `in` filters you are squishing it into a string. I try to avoid doing that in the UI as it can lead to accidental sql injection (eg if you put a ; in your value).

I think if `filter.value` is made an array it should work. It will need a few more changes:

- change TableFilter in src/lib/models, so that the type of `value` is `string | string[]`
- add a test case in `tests/lib/db.ts#filterTests` to cover the `in` condition. This will make sure it works across all databases

Thanks for contributing!

2022-03-11 20:42 UTC, rathboma requested changes
see comment above

2022-04-14 19:57 UTC, rathboma commented
@yogski checking to see if you have time to make these changes, or do you need me to take the PR over?

2022-04-22 19:58 UTC, closed without merging

2022-07-09 18:44 UTC, ianberryman commented
@rathboma I see your comment above, I'll update this PR unless you think a new one would be better lmk

2022-07-09 18:48 UTC, ianberryman commented
Duh nm, I've got my own fork