#1484 - Editing Disabled message.
beekeeper-studio/beekeeper-studio pull request #1509
Opened 2023-02-17 20:06 UTC by not-night-but

Fix #1484, Message now reads "Editing Disabled" and the tooltip has been changed to reflect this:

![image](https://user-images.githubusercontent.com/58712803/219782624-dc3934e4-64de-4162-ad1f-ca8a00e049ca.png)

2023-02-21 03:14 UTC, rathboma commented on apps/studio/src/components/tableview/TableTable.vue
> +        "Tables without a primary key column only support insert and delete. Editing of existing records is disabled."
Actually they don't support delete :-)

2023-02-21 03:14 UTC, rathboma requested changes
delete isn't supported actually!

2023-02-21 03:22 UTC, not-night-but commented
@rathboma agh my bad 🤦

2023-02-22 03:55 UTC, rathboma approved these changes

2023-02-22 03:55 UTC, merged