1472 selectable fields
beekeeper-studio/beekeeper-studio pull request #1512
Opened 2023-02-18 04:53 UTC by not-night-but

Fix #1472. Now this tooltip will show when a column name cannot be edited:
![image](https://user-images.githubusercontent.com/58712803/219835086-bcb5a3f0-b952-431a-8c69-e9d015222234.png)

And the user can click the column name to copy it to clipboard

2023-02-21 03:38 UTC, rathboma commented
Can we also add the `selected` style that we use for non-editable cells in the TableTable view?

![Peek 2023-02-20 21-38](https://user-images.githubusercontent.com/279769/220241480-e2350d3e-f921-4be1-bd7a-9b14c47e7afc.gif)

2023-02-21 03:39 UTC, rathboma requested changes
Looks good, but for consistency, lets add the cell-selected style we use in TableTable too.

2023-02-28 03:45 UTC, rathboma commented on apps/studio/src/components/tableinfo/TableSchema.vue
> +    columnNameCellClick(_e: any, cell: CellComponent) {
If you click away from the table does it unselect the cell? Take a look at table table for how to do that.

2023-03-03 18:23 UTC, rathboma requested changes
This needs to handle the case when someone clicks away from the cell, in that case it should de-select it. See how we do this in tabletable (we add a global click watcher).

2023-03-04 05:01 UTC, not-night-but commented
@rathboma handling global clicks now

2023-03-09 04:12 UTC, rathboma approved these changes
Actual change looks good! Need to fix the weird other changes before merging though.

2023-03-09 04:29 UTC, not-night-but commented
> The diff on the pr looks like it has a bunch of other changes in it? Can you merge in master and push up?
> 
> this might be a GitHub oddity

Actually looking at the commit history I'm super confused as to what's happened. I try to keep my branches up to date with main, something must've happened during one of the merges?

2023-03-09 05:44 UTC, merged