Copy to sql
beekeeper-studio/beekeeper-studio pull request #1541
Opened 2023-03-09 06:54 UTC by not-night-but

Close #1534 

Copy to SQL for data view.
I mainly went off of the implementation for this feature in the tableSchema view.

Note: ran into an issue with updating data in sqlite tables, was an issue with the knex client, it is fixed now, but seems kinda hacky to me.

Still have some cleaning up to do.

2023-03-12 02:47 UTC, rathboma requested changes
Great work!

super minor change requested.

This also needs a basic integration test to at least call the function and check some basic text is present. Don’t try and match the whole string, just look for “insert”, etc.

also, when you merge this you’ll need to add support to Cassandra and oracle in the ultimate edition.

2023-03-12 02:47 UTC, rathboma commented on apps/studio/src/lib/db/client.ts
> +  getChangesSql: (changes: TableChanges) => Promise<string>,
These changes look great.

one nitpick: to be consistent with the other methods where we have a x, and a xSql can we name it applyChangesSql?

2023-03-16 03:38 UTC, not-night-but commented
@rathboma Changes made.  I also made applyChangesSql synchronous, as it doesn't actually need to be async at all.

2023-03-18 02:10 UTC, rathboma approved these changes
🎉

2023-03-18 02:10 UTC, merged