Feat: duplicate table
beekeeper-studio/beekeeper-studio pull request #1543
Opened 2023-03-11 01:18 UTC by lanzoninicola

The new feature adds an item to the contextual menu that appears when the user right-clicks on a table. This item allows the user to duplicate the table, copying both the structure and the data (except indexes, triggers, constraints) (it works doing a "select * into <new_table>" from <old_table>).

The video that has been provided demonstrates how the feature works in action, allowing users to see exactly how the new functionality will benefit them. Overall, this feature should make it much easier and more efficient for users to duplicate tables, saving them time and effort in their database editing work.

Link to the video: https://youtu.be/cn0dG4YSIZk

2023-03-12 03:07 UTC, rathboma requested changes
Fantastic PR thanks so much!

I’ve added a couple of requests inline with the code.

one last ask:
would you be able to add an integration test in the db.ts and all.is file? That way we can make sure it works for all databases we add going forward :-)

2023-03-12 03:07 UTC, rathboma commented on apps/studio/src/components/CoreTabs.vue
> +            await this.connection.duplicateTable(tableName, this.duplicatedTableName, schema)
Do you need to clear duplicatesTableName and duplicatedTableParams here in a finally block?

2023-03-12 03:07 UTC, rathboma commented on apps/studio/src/lib/db/client.ts
> +  // duplicate table
Could you possibly also add a ‘duplicateTableSql’ method here (similar to alterTableSql vs alterTable) so users can edit the sql themselves if they like?

2023-03-12 03:07 UTC, rathboma commented on apps/studio/src/lib/db/clients/mysql.js
> +  let sql = `CREATE TABLE ${wrapIdentifier(newTable)} LIKE ${wrapIdentifier(tableName)};`;
I didn’t even know about this syntax! Thanks for this

2023-03-13 12:33 UTC, lanzoninicola commented on apps/studio/src/components/CoreTabs.vue
> +          <button @focusout="sureOpen && $refs.no && $refs.no.focus()" @click.prevent="completeDuplicateTableAction" class="btn btn-sm btn-primary">{{this.titleCaseAction}} {{this.dbElement}}</button
Thank you for all your comments, I will work on it in the next few days....

2023-03-18 18:51 UTC, lanzoninicola commented
> 

I'm glad you like it. If all goes well, I should be able to let you know next week when the updated version is ready for your review.

2023-03-23 13:05 UTC, lanzoninicola commented
Hello @rathboma,
I have finished all the tasks that were assigned to me and have also included the tests as per your suggestion. If you are ready to move forward with the review, I would greatly appreciate it.
Thank you.

2023-04-27 02:52 UTC, rathboma approved these changes
Amazing! Sorry it took so long, it's been a rough Q1 :-)

2023-04-27 02:58 UTC, merged