fix: add a default column name title of Result
beekeeper-studio/beekeeper-studio pull request #1690
Opened 2023-09-04 18:51 UTC by wmontgomery

fix #1662

![record-count](https://github.com/beekeeper-studio/beekeeper-studio/assets/314613/6c0fd689-c840-4f43-8b29-6d70e4a8d623)

2023-09-04 21:27 UTC, not-night-but approved these changes

2023-09-04 21:27 UTC, not-night-but commented on apps/studio/src/components/editor/ResultTable.vue
> +          console.log(column.name)
I'd just get rid of the logs here

2023-09-05 22:08 UTC, rathboma requested changes
just kill the logs and we're good to go!

2023-09-08 01:14 UTC, wmontgomery commented on apps/studio/src/components/editor/ResultTable.vue
> +          console.log(column.name)
Oops. Consider them gone!

2023-09-08 01:21 UTC, wmontgomery commented
> what if there are multiple unnamed columns? Are they all `Result`?

Yeah there would be. It's not a frequent case (at least I hope not as you should be aliasing your columns). I can add some kind of counter to it if wanted. That's actually fairly easy since it's a map.

Something like this just to get the index in there
```js
return this.result.fields.map((column, index) => {
  const result = {
    title: column.name || `Result ${index}`,
```

2023-09-08 14:52 UTC, rathboma approved these changes

2023-09-08 14:52 UTC, merged