Leave aliases to be unquoted in autocomplete
beekeeper-studio/beekeeper-studio pull request #1740
Opened 2023-10-14 07:07 UTC by azmy60

Testing CodeMirror outside of bks a just little bit. It turns out that this behavior was not from the CodeMirror itself😅 .

Fixes point 2 in #1721

2023-10-14 07:36 UTC, not-night-but requested changes
@azmy60 Nice! Glad we got this one figured out. 

Code looks good, but do you think you could add some regression tests for this?

2023-10-14 08:48 UTC, azmy60 commented
Oh yeah, forgot that one. Let me see if I can do it.

2023-11-08 22:46 UTC, rathboma reviewed
Looks good, question: is this a problem in other dialects?

2023-11-08 22:46 UTC, rathboma commented on apps/studio/src/lib/codemirror.ts
> +  if (!instance.getOption("mode").includes("pgsql")) return;
Quoting aliases isn't a problem in the other languages?

2023-11-08 22:47 UTC, rathboma commented
Ok for you to merge, but if also a problem in other dialects, they'll need sorting also. eg SQL Server has schemas + tables also

2023-11-26 18:46 UTC, rathboma commented on apps/studio/src/lib/codemirror.ts
> +  if (!instance.getOption("mode").includes("pgsql")) return;
@azmy60 quick check-in for this question. If this isn't a problem, feel free to merge plz

2023-11-26 18:46 UTC, rathboma approved these changes
Feel free to merge this, but check my question first!

2023-11-27 06:39 UTC, azmy60 commented
Redshift needs the autoquote too so that's added. Merging now :)

2023-11-27 06:50 UTC, azmy60 commented
hmm.. I can't merge it somehow 🤔

2023-12-04 21:28 UTC, merged