SQLite client
beekeeper-studio/beekeeper-studio pull request #1764
Opened 2023-10-27 16:21 UTC by not-night-but

Close #1739

2023-11-15 23:00 UTC, rathboma requested changes
Awesome work Day! Great stuff. Only minor changes needed:

Let's not use `as` and just have two methods. Also - remove the stuff you told yourself to remove :-)

You have a bunch of notes about broken or incomplete things. Can they be dealt with or better notes left?

2023-11-15 23:05 UTC, not-night-but commented on apps/studio/src/lib/db/clients/sqlite.ts
> +    return Promise.resolve([]); // TODO: not implemented yet
That was the same thing in the old driver

2023-11-15 23:05 UTC, not-night-but commented on apps/studio/src/lib/db/clients/sqlite.ts
> +  // NOTE (@day): This may need some more work
I thought I removed this note lol, is very old

2023-11-15 23:06 UTC, not-night-but commented on apps/studio/src/lib/db/clients/sqlite.ts
> +    const db = new Database(`${fileLocation.join('/')}/${databaseName}.db`)
Good catch. I always forget windows likes to be different

2023-11-15 23:07 UTC, not-night-but commented on apps/studio/src/lib/db/clients/sqlite/SqliteCursor.ts
> +// TODO (@day): remove this interface, I think it might be useless now
Dope

2023-11-15 23:07 UTC, not-night-but commented on apps/studio/src/lib/db/clients/sqlite.ts
> +    throw new Error("Method not implemented.");
I think that's a good idea. Would be super useful for the readonly clients as well

2023-11-16 22:47 UTC, not-night-but commented on apps/studio/src/lib/db/clients/sqlite.ts
> +    const { data } = await this.driverExecuteQuery(sql) as SqliteResult;
Alrighty, I'll just modify the base class

2023-11-17 21:15 UTC, rathboma approved these changes
Looks good. Let's merge it.

2023-11-17 21:15 UTC, merged