feat (sqlite): support updating rows with internal primary keys
beekeeper-studio/beekeeper-studio pull request #1795
Opened 2023-11-20 12:42 UTC by azmy60

fix #1532

2023-11-23 11:21 UTC, azmy60 commented
I just tested oracle in ultimate. Unfortunately the `getInternalPrimaryKey` approach is kind of not suitable to oracle. But instead, I'm thinking about adding `rowid` option to the `selectTop` function. And then put the `rowid` name of each database to the dialects (many databases have different `rowid` name).

2023-12-04 18:11 UTC, azmy60 commented
I used his [branch](https://github.com/beekeeper-studio/beekeeper-studio/compare/master...davidkaufman:beekeeper-studio:issue-issue-1532-editing-tables-with-rowids) at first but there were a lot of stuff to change so I ended up starting over to keep it a bit cleaner.

2023-12-07 03:18 UTC, rathboma requested changes
Hey, I think you've done a good job here, but I'm not sure I actually want to merge this feature for postgresql.

From the PostgreSQL docs: [ctid isn't always stable](https://www.postgresql.org/docs/current/ddl-system-columns.html) - `a row's ctid will change if it is updated or moved by VACUUM FULL`.

I'm OK with the SQLite implementation, but I think we should remove the PostgreSQL one.

2023-12-07 03:20 UTC, rathboma commented
Note from the Oracle docs on ROWID:

```
You should **not** use ROWID as the primary key of a table. If you delete and reinsert a row with the Import and Export utilities, for example, then its rowid may change. If you delete a row, then Oracle may reassign its rowid to a new row inserted later. 
```
from https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ROWID-Pseudocolumn.html#GUID-F6E0FBD2-983C-495D-9856-5E113A17FAF1

2023-12-08 18:01 UTC, davidkaufman commented
Yes Oracle, PG and SQL Server all say similar things such as "this internal row id is not to be relied upon not tot change" as PG says, after a VACUUM, Oracle and SQL Server say it may change after a backup & restore, but all of the discussions I saw of these on StackOverflow, etc. users reported that they were stable and reliable enough for exactly our use case here: being able to update a row in a table without a primary key, in a table you just queried.

2023-12-13 19:25 UTC, rathboma commented
I think they are reliable enough 99.9% of the time, but the 0.1% of the time when someone is updating a production database and it overwrites the wrong row -- not worth it to me. I don't want Beekeeper Studio depending on `good enough` semantics with something so important.

2023-12-13 19:27 UTC, rathboma commented on apps/studio/src/lib/db/client.ts
> +  getInternalPrimaryKey: (db: string, table: string, schema?: string) => Promise<InternalPrimaryKey>,
This should be `Promise<InternalPrimaryKey | null>`

2023-12-13 19:29 UTC, rathboma requested changes
let's remove the psql implementation, then we can merge for sqlite

2023-12-13 19:29 UTC, rathboma commented on apps/studio/src/lib/db/clients/postgresql.ts
> +export async function getInternalPrimaryKey(conn: HasPool, database: string, table: string, schema: string): Promise<InternalPrimaryKey | null> {
We need to kill this, no?

2024-01-19 17:29 UTC, rathboma commented
@azmy60 question. Instead of making all these changes to the UI for a single DB client, what if SQLite just returned the secret primary key as the primary key for tables that don't have an explicit one? Then we'd need no UI changes right?

2024-01-19 17:56 UTC, azmy60 commented
@rathboma Sounds like this is a special behavior for SQLite only. Which is good and it's possible to do that I think. I guess we don't have to show the secret primary key to the table too? Or show it in a way that tells it's a "secret primary key".

2024-01-19 20:52 UTC, rathboma commented
I think if we just show it as a normal PK as `rowid` with a special column header tooltip explaining it's automatically provided by sqlite.

Only show it where a primary key hasn't been defined otherwise.

Yeah special behavior just for SQLite.

2024-01-19 22:07 UTC, azmy60 commented
Ok. That's much simpler than the current implementation. Love that lol.

2024-01-22 00:09 UTC, rathboma commented
@azmy60 going to close this in favor of just making the SQLite `rowid` visible, that can be a separate PR

2024-01-22 00:09 UTC, closed without merging