Feature/1738 readable date time
beekeeper-studio/beekeeper-studio pull request #1835
Opened 2023-12-26 18:57 UTC by wmontgomery

#1738 
<img width="453" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/314613/4d35a640-4d25-49bb-bfe5-e98dc63bbf4e">

2024-01-19 21:11 UTC, rathboma commented
Hey Will,

Can we remove the icon and just make the title something like `${datetime} in unixtime`?

2024-01-21 04:16 UTC, wmontgomery commented
You betcha.

On Fri, Jan 19, 2024, 16:12 Matthew Rathbone ***@***.***>
wrote:

> Hey Will,
>
> Can we remove the icon and just make the title something like ${datetime}
> in unixtime?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/beekeeper-studio/beekeeper-studio/pull/1835#issuecomment-1901121149>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACMZ5NT357PVPUPB6IFLSDYPLOSNAVCNFSM6AAAAABBDREOUSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBRGEZDCMJUHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-28 20:42 UTC, wmontgomery commented
<img width="423" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/314613/fe3c67ae-795f-4071-9026-6b7189918487">

2024-02-08 20:41 UTC, rathboma requested changes
Error catching, html escaping, then done

2024-02-08 20:41 UTC, rathboma commented on apps/studio/src/mixins/data_mutators.ts
> +    return `<div class="cell-link-wrapper" title="${tooltip}">${cellValue}</div>`
These dynamic values need HTML escaping

2024-02-08 20:41 UTC, rathboma commented on apps/studio/src/mixins/data_mutators.ts
> +        tooltip = `${new Date(Number(cellValue)).toISOString()} in unixtime`
What if this fails? We should error catch here and set a default tooltip

2024-02-14 16:23 UTC, rathboma commented on apps/studio/src/mixins/data_mutators.ts
> +          console.error(`${cellValue} cannot be converted to a date`)
You should log the error here too

2024-02-14 16:24 UTC, rathboma approved these changes

2024-02-14 16:24 UTC, merged