add row as array flag to sqlite `executeQuery`
beekeeper-studio/beekeeper-studio pull request #1981
Opened 2024-02-26 18:17 UTC by azmy60

fix #1978, fix #1976

2024-03-06 22:24 UTC, rathboma requested changes
This should have a new integration test to make sure queries that return duplicate column names work right!

2024-03-07 02:28 UTC, azmy60 commented
Doesn't `queryTests` cover the duplicate columns? I removed the filter to run `queryTests` from `sqlite`.

2024-03-07 14:55 UTC, rathboma commented
Oh, does it? If so then good to merge

2024-03-07 14:55 UTC, rathboma approved these changes

2024-03-08 11:27 UTC, merged