Feature/2029 autocomplete documentation
beekeeper-studio/beekeeper-studio pull request #2143
Opened 2024-04-21 18:35 UTC by wmontgomery

resolves #2029 
<img width="1179" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/314613/c398e204-6d59-4434-8120-7584c17c82f3">

<img width="1174" alt="image" src="https://github.com/beekeeper-studio/beekeeper-studio/assets/314613/d2088112-a415-440e-9dee-f7de0794f988">

2024-04-23 14:53 UTC, rathboma requested changes
Too many shortcuts listed there right now.

- Find and replace is on the shortcut list twice, can you remove the incorrect one?
- Also Remove the 'run query to file' lines.

2024-05-08 17:56 UTC, rathboma commented
@wmontgomery ping

2024-06-03 19:04 UTC, wmontgomery commented
Oops, just saw these pings today. I'll get them fixed up.

2024-09-13 18:18 UTC, rathboma approved these changes

2024-09-27 13:18 UTC, merged