Azure auth
beekeeper-studio/beekeeper-studio pull request #2175
Opened 2024-05-03 17:52 UTC by not-night-but

Fix [azure sso auth](https://github.com/beekeeper-studio/ultimate/issues/72)

First pass at this, definitely still some stuff to work on, but I'm wanting some feedback.

# TODO
- [ ] Figure out what happens if perms expire/are revoked with an active connection. May need to add reauthentication to the error handler on the pool.

# NOTES
- I just have the clientid hardcoded in the azureAuthService (it is inserted as plaintext in the url, so not exactly a secret?)
- To actually test this, you'll have to comment out the ultimate checking in SqlServerForm

2024-05-10 00:04 UTC, rathboma commented
@ellipsis-dev code review please

2024-05-13 03:00 UTC, rathboma requested changes
Looks awesome! Super clean.

had a a about foreign keys, plus a couple of nits, but otherwise good

2024-05-13 16:09 UTC, not-night-but commented on apps/studio/src/components/ConnectionInterface.vue
> +          this.config.azureAuthOptions.authId = cache.id;
@rathboma I've moved it, but sqlite doesn't support adding relations after the table has been created. If we really want to do it I could write a script to recreate the table with that fk, up to you

2024-05-15 14:21 UTC, rathboma commented on apps/studio/src/components/ConnectionInterface.vue
> +          this.config.azureAuthOptions.authId = cache.id;
@not-night-but just change your migration to do it the way we want, then kill your ~/.config/beekeeper-studio/app-dev.db to test it

2024-05-15 14:22 UTC, rathboma commented
@not-night-but if you fix merge conflicts, and then fix the migration, we can merge this and release it!

2024-05-15 14:34 UTC, not-night-but commented on apps/studio/src/components/ConnectionInterface.vue
> +          this.config.azureAuthOptions.authId = cache.id;
@rathboma sorry I'm confused. Don't you want the FK on saved/used connections?

2024-06-06 21:56 UTC, rathboma approved these changes
Let's gooooo

2024-06-06 21:56 UTC, merged

2024-06-20 14:41 UTC, vamsitp commented
Any plan to provide Azure AD (SSO) support for Azure PGSQL too?

2024-06-20 15:07 UTC, rathboma commented
I didn't even know that was a thing, but yes we can do that :-)

2024-06-20 15:52 UTC, vamsitp commented
https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/azure-active-directory-authentication-in-azure-postgresql/ba-p/3723066