[Fix] Add exit confirmation modal before quitting
beekeeper-studio/beekeeper-studio pull request #2209
Opened 2024-05-17 01:57 UTC by H0onnn

## Issue

- close #2201 

## Work Detail

I modified it so that you can check the confirmation alert when the application is terminated using electron's default dialog.

If I need to use a custom modal in Vuejs, I need some advice on how to do that.

Thanks !

## Preview

![image](https://github.com/beekeeper-studio/beekeeper-studio/assets/116232939/55a3f96f-f383-4946-b7d8-53b7a5094fe0)

2024-06-03 17:09 UTC, rathboma commented
Hey, thanks for this! I think we need a way to disable this warning, as many folks might find it frustrating. Is that possible with the electron API?

2024-06-04 00:57 UTC, H0onnn commented
Hello, @rathboma :)

Are you talking about the toggle? I'll give it a try.

2024-10-02 16:23 UTC, rathboma requested changes
Ok, here's what I think:

- Adding a warning is a good idea, but only if users have UNSAVED changes.

I don't want it to always warn the user regardless, as this is super annoying.

Is this possible for you to work on?

2025-03-16 16:38 UTC, rathboma commented
Closing this, don't think we want to do this at all.

2025-03-16 16:38 UTC, closed without merging