Fix Postgres malformed array literal errors on indexes
beekeeper-studio/beekeeper-studio pull request #2392
Opened 2024-08-31 05:23 UTC by Kratious

fix #1334 

The main issue is the expression text to array conversion happening in `(('{' || pg_get_expr(i.indexprs, i.indrelid)|| '}')::text[])[k.i]`. Commas in an expression become delimiters and split the expression up prematurely. Double quotes and other special characters may cause the malformed array literal errors.

The postgres function `pg_get_indexdef` does what the snippet above trying to do, but safely.

Here's a minimal test case I ran through:

Table
```
CREATE TABLE
  public.test_indexes (
    first_name text NOT NULL,
    last_name text NOT NULL,
    data jsonb NOT NULL DEFAULT '{"a": {"b": ["foo", "bar"]}}'::jsonb
  );
```

Indexes
```
CREATE INDEX single_column ON test_indexes (first_name);
CREATE INDEX multi_column ON test_indexes (first_name, last_name);

CREATE INDEX single_expression ON test_indexes (lower(first_name));
CREATE INDEX multi_expression ON test_indexes (lower(first_name), lower(last_name));

CREATE INDEX expression_with_comma ON test_indexes ((lower(first_name) || ', ' || lower(last_name)));
CREATE INDEX expression_with_double_quote ON test_indexes (('"' || first_name));
CREATE INDEX expression_with_jsonb_operator ON test_indexes ((data #>> '{a,b,1}'));
```

In `View Structure -> Indexes`:
![image](https://github.com/user-attachments/assets/ff793b94-83ea-4962-b8a1-c6351a886cc2)

2024-09-14 16:08 UTC, rathboma requested changes
This is wonderful, thank you!

Would you please add a test for this, so that we don't change something in the future and accidentally break your fix?

You can add code to `apps/studio/tests/integration/lib/db/clients/postgres.spec.ts`

It's fairly simple to add a table in the `beforeAll`, and then add a test to make sure the method works.

2024-09-16 14:51 UTC, Kratious commented
I wasn't able to get the integration tests running on my machine, so I can't attest to the test's correctness 🙂

2024-10-04 20:19 UTC, rathboma commented
Thanks so much for this and sorry for the late review.

It looks good, but I think it will probably break `redshift.ts` and `cockroach.ts` - both are downstream clients that depend on the Postgres client implementation of this function.

Also looks like the test is broken.

You should be able to run the tests locally using:

`yarn test:integration postgres`

2024-10-04 20:19 UTC, rathboma requested changes
Broken test and likely this will break redshift & cockroachdb?

2024-10-14 19:12 UTC, AykutCevik commented
Came into this exact issue while creating an index on Postgres and viewing the table structure in Beekeeper:
```sql
CREATE INDEX table_idx ON table USING GIN (
    (
        setweight(to_tsvector('english', coalesce(col1, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(col2, '')), 'B')
    )
);
```

Now, Beekeeper is not able to view the structure of the table anymore. Works in DBeaver though.

2024-12-24 06:03 UTC, bqrkhn commented
I'm also facing this issue.  `data` is a `jsonb` column.

![Capture-2024-12-24 at 11 31 04](https://github.com/user-attachments/assets/9da9d723-e31c-439a-b333-d0e46eec16be)

2025-01-03 03:22 UTC, rathboma commented
@not-night-but Hoping you can step in to take over this bug fix?

2025-01-13 19:02 UTC, not-night-but commented
@rathboma I've fixed the tests, updated the branch, and tested on cockroach and redshift. Cockroach works like a dream, and we don't actually support indexes on redshift so this seems like it should be good to go!

2025-03-16 17:00 UTC, rathboma commented
@not-night-but doesn't look like the test checks the output of indexes with array literals? Please fix the test then good to merge

2025-04-05 21:47 UTC, rathboma commented
@not-night-but can you wrap this up ready for the 5.2 release?

2025-05-02 11:42 UTC, azmy60 commented
@rathboma @not-night-but I just fixed the merge conflicts and added tests that check the output of indexes with array literals, though I couldn't make it very specific with the content of the array literals because it returns limited info, but it should be good enough I think.

2025-05-09 18:12 UTC, not-night-but approved these changes

2025-05-09 18:12 UTC, merged