Fix Logging
beekeeper-studio/beekeeper-studio pull request #2527
Opened 2024-10-23 21:23 UTC by not-night-but

Biggest change here is that we will no longer import from `electron-log`. There is now an alias `@bksLogger` which will import the correct file. This also means that the proper settings for logging will be applied for every logger, no matter what. 

Utility logs will no longer appear in the devConsole, only in the terminal in dev mode. They also now go to their own file called `utility.log` in the logs folder.

I've also modified the format (mostly just to know that I could, but also to make it clear in the terminal which process the logs are coming from). Unfortunately there doesn't seem to be an easy way to format renderer logs when they appear in the terminal, I can also turn those logs off if we want (ie renderer logs would only be in the dev console, and only main and utility would be in the terminal).

2024-10-26 13:37 UTC, rathboma requested changes
This looks good, but a couple of open questions:
1. How do you prevent folks from importing electron-log (think about someone new to the project in 12 months time)?
2. How do you prevent renderer / utility folks from importing the wrong version of bksLogger?

2024-10-26 13:37 UTC, rathboma commented on apps/studio/src-commercial/entrypoints/main.ts
> +import log from '@/lib/log/bksLogger'
you don't want this to be @bksLogger?

2024-10-29 00:23 UTC, not-night-but commented on apps/studio/src-commercial/entrypoints/main.ts
> +import log from '@/lib/log/bksLogger'
Oops, missed this

2024-10-29 00:26 UTC, not-night-but commented
@rathboma In regards to your questions, I think both of them could be solved with an eslint rule (although I'm not sure how much we actually use eslint), or with a github workflow to ensure that electron-log is not imported, and that only `@bksLogger` is imported.

2024-11-15 03:10 UTC, azmy60 reviewed
This looks great! We probably just need to have something that checks if someone use the right logger or not. I could see that's something I can probably forget 😆

2025-01-13 19:58 UTC, rathboma commented
@not-night-but fix merge conflicts and merge it!

2025-01-13 20:28 UTC, merged