Feature/upsert for import take 2
beekeeper-studio/beekeeper-studio pull request #2535
Opened 2024-10-27 14:59 UTC by wmontgomery

resolves #2158 
![2158](https://github.com/user-attachments/assets/5bd46c9b-84d8-44b9-bb0c-440fc07a3d4a)

2025-01-31 14:56 UTC, azmy60 requested changes
Just found a regression on generating query with `copy as SQL`. Overall, looks awesome!

2025-01-31 14:56 UTC, azmy60 commented on apps/studio/src/lib/db/clients/BasicDatabaseClient.ts
> +    return buildInsertQuery(this.knex, tableInsert, { columns, runAsUpsert, primaryKeys, createUpsertFunc: this.createUpsertFunc });
It looks like we are missing a deserialization. `tableInsert` needs to be deserialized so knex can generate the right query (especially with buffer types). I missed adding the query test for buffers but you can also test this from the table view by right-clicking a row -> `copy as SQL`. This is a sample SQLite table with buffers:

```sql
CREATE TABLE test_table (id INTEGER PRIMARY KEY AUTOINCREMENT, data BLOB NOT NULL);
INSERT INTO test_table (data) VALUES (X'DEADBEEF'), (X'CAFEBABE');
```

P.S. I hate that the deserialization does nested loop like that :). There must be a better way probably.

2025-02-04 03:18 UTC, wmontgomery commented on apps/studio/src/lib/db/clients/BasicDatabaseClient.ts
> +    return buildInsertQuery(this.knex, tableInsert, { columns, runAsUpsert, primaryKeys, createUpsertFunc: this.createUpsertFunc });
@azmy60 , looks like a snippet got lost probably in one of the million merge conflicts that happened since starting this :D I added the snippet back and got the expected behavior.

2025-02-04 06:21 UTC, azmy60 commented on apps/studio/src/lib/db/clients/BasicDatabaseClient.ts
> +    return buildInsertQuery(this.knex, tableInsert, { columns, runAsUpsert, primaryKeys, createUpsertFunc: this.createUpsertFunc });
😆 thanks!

2025-02-04 06:23 UTC, azmy60 approved these changes

2025-02-04 18:55 UTC, rathboma commented
@wmontgomery how to folks choose to upsert / insert? Is there an option in the import flow?

2025-02-12 19:20 UTC, merged