Feature/2379 tab history
beekeeper-studio/beekeeper-studio pull request #2641
Opened 2024-12-12 02:35 UTC by wmontgomery

![tabs-history](https://github.com/user-attachments/assets/59c913b4-9528-495b-a587-8cd625d7f05e)

2024-12-20 04:00 UTC, sharandeepak1211 commented
Shall we have a key binding to move between tables like "CMD + ]" for moving forward and "CMD + [" for moving backward ?
Because this is a universal shortcut in MAC for these purpose. It will be super handy to navigate : )

@rathboma @wmontgomery

2025-01-03 03:38 UTC, rathboma requested changes
This looks awesome! So excited to get this into Beekeeper Studio.

Big question is around -- can we do this without duplicating tab data to another model?

Also -- can you implement a `Reopen Closed Tab` function in the right click menu for tabs using this data?

2025-01-03 03:38 UTC, rathboma commented on apps/studio/src/common/appdb/models/TabHistory.ts
> +export class TabHistory extends ApplicationEntity {
Hey, I think the changes here look pretty good, and it's a slick experience using this.

Only question I have: Do we really need a new model to handle this, or can we just add a few more details to the `OpenTab` model, or even do it without changing OpenTab much at all?

Is this a stupid question, or could we do this by:

1. Adding `lastActiveAt` to OpenTab (time the user last clicked it)
2. Add `deletedAt` to OpenTab (time the user closed it). Then we set this instead of deleting the opentab
3. Adding an index to [deletedAt, workspaceId, connectionId]
4. Almost everything can then be done in the front-end. we just need a way to load recentlyClosed tabs at app start, then they can just be added to the recentlyClosedTabs stack when someone closes them.
5. On start, delete any `OpenTab` models with `deletedAt` < 3 days ago

Would this save a lot of duplication? Am I being naive and missing something big?

2025-01-09 02:07 UTC, wmontgomery commented on apps/studio/src/common/appdb/models/TabHistory.ts
> +export class TabHistory extends ApplicationEntity {
I wanted to keep Open Tabs exactly what they are: Tabs that are open and active. I didn't want to add any logic to the open tabs model for either maintaining a certain history (open and closed to be reopened). Having the additional model does have some duplicated pieces, no doubt there, but it's largely for historic reasons and keeping the open tabs model pure.

I had hoped to keep as much out of the front end as possible to not muddy the store up as well.

2025-01-31 08:56 UTC, azmy60 commented on apps/studio/src/store/modules/TabModule.ts
> +        tabs = tabs.filter(tab => !tab.deletedAt)
I know we can't really pass `deletedAt` to options from here so this is good for now. In the future, we might wanna filter deleted rows by default like using [@deleteDateColumn](https://typeorm.io/select-query-builder#querying-deleted-rows) if that doesn't break other parts of the app. Or something like `appdb/tabs/findExceptDeleted`.

2025-01-31 09:17 UTC, azmy60 requested changes
This is awesome! One little issue when reopening the closed tab, the opened tab is not focused and I can't close it by pressing `Ctrl+w`.

![history-tab](https://github.com/user-attachments/assets/af5de6b4-9773-420c-a8f9-0e6dd5780fdb)

2025-02-01 16:03 UTC, wmontgomery commented on apps/studio/src/store/modules/TabModule.ts
> +        tabs = tabs.filter(tab => !tab.deletedAt)
oh good catch. I didn't even know about this.

2025-02-03 10:17 UTC, azmy60 approved these changes

2025-02-09 03:52 UTC, rathboma requested changes
let's add a couple of indexes to make sure OpenTab queries remain fast, then I'm good to merge!

2025-02-09 03:52 UTC, rathboma commented on apps/studio/src/migration/20251116_tab_history_updates.js
> +      `ALTER TABLE tabs ADD COLUMN lastActive datetime`,
We'll need to add a reverse index to `lastActive`, seeing as you're using it in a DESC search.

2025-02-09 03:52 UTC, rathboma commented on apps/studio/src/migration/20251116_tab_history_updates.js
> +      `ALTER TABLE tabs ADD COLUMN lastActive datetime`,
Probably also need an index on the deletedAt column

2025-02-11 04:53 UTC, wmontgomery commented on apps/studio/src/migration/20251116_tab_history_updates.js
> +      `ALTER TABLE tabs ADD COLUMN lastActive datetime`,
sure thing

2025-02-18 14:10 UTC, rathboma commented on apps/studio/src/common/appdb/models/OpenTab.ts
> +export const TabHistoryHandlers = {
@not-night-but is this in the right place? Where should will put this object?

2025-02-18 14:31 UTC, wmontgomery commented on apps/studio/src/common/appdb/models/OpenTab.ts
> +export const TabHistoryHandlers = {
I've seen them in their own file before. I want to say I've seen them in the same file as the model but I could have also done that when I had the tab history model set up. I can move them if it's the wrong spot. Was going to keep them close in file structure to each other since they expand nowhere else.

2025-02-19 22:00 UTC, not-night-but commented on apps/studio/src/common/appdb/models/OpenTab.ts
> +export const TabHistoryHandlers = {
@wmontgomery Yeah these should be in the handlers directory. Ideally in their own file called `tabHistoryHandlers.ts` in `src/handlers/`

2025-03-16 16:37 UTC, rathboma approved these changes

2025-03-16 16:37 UTC, merged