fix mysql binary parsing the wrong columns
beekeeper-studio/beekeeper-studio pull request #2661
Opened 2024-12-17 23:33 UTC by not-night-but

Tentative fix for properly parsing mysql column types for binary parsing

2024-12-18 05:49 UTC, azmy60 requested changes
LGTM! Just one little cleanup and we're good.

2024-12-18 05:49 UTC, azmy60 commented on apps/studio/src/lib/db/clients/mysql.ts
> -    const fields = this.parseQueryResultColumns(result);
We can remove `parseQueryResultColumns` if we're not using it.

2024-12-18 16:10 UTC, rathboma approved these changes

2024-12-18 16:35 UTC, merged

2024-12-19 06:39 UTC, React1-X commented
Hi, I downloaded the latest version off the website (5.0.8) - I'm still getting this issue. I'm not sure if this new build has been published to the website or not. Thanks!