Implement table length function
beekeeper-studio/beekeeper-studio pull request #2673
Opened 2024-12-20 22:37 UTC by anilsenay

`getTableLength` function implemented for Cassandra

2025-01-13 18:24 UTC, rathboma requested changes
Is this expensive?

2025-01-13 18:24 UTC, rathboma commented on apps/studio/src-commercial/backend/lib/db/clients/cassandra.ts
> +    const rowCount = await this.getTableLength(table)
Hey! One of the reasons we didn't implement it (although we should have added this to the comments) is that the count(*) operation can be very expensive for Cassandra -- as it has to scan all the table rows. Is there a more efficient way to get this information?

2025-01-13 18:39 UTC, anilsenay commented on apps/studio/src-commercial/backend/lib/db/clients/cassandra.ts
> +    const rowCount = await this.getTableLength(table)
@rathboma Hey, thank you for the information; I didn't know that.

As you said, it was expensive based on this post: https://www.datastax.com/blog/running-count-expensive-cassandra. They suggested some ways in post but they are not suitable.

Since there is no better way for now, i guess we can close the pull-request.

2025-01-20 16:01 UTC, rathboma commented on apps/studio/src-commercial/backend/lib/db/clients/cassandra.ts
> +    const rowCount = await this.getTableLength(table)
Kk

2025-01-20 16:02 UTC, closed without merging