Added the option to remove (multiple) saved queries and queries from the history
beekeeper-studio/beekeeper-studio pull request #308
Opened 2020-08-29 23:54 UTC by UtechtDustin

Added the option to remove (multiple) saved queries and queries from the history

Fix #305

![Peek 2020-08-30 01-52](https://user-images.githubusercontent.com/13292481/91648096-a76fb800-ea63-11ea-94ac-d4b437b7ba86.gif)

2020-08-29 23:56 UTC, UtechtDustin commented
@rathboma 
It's working fine for the saved queries, so i tried to implement the same for the quries in the history but i get the error
```
 Property or method "discardCheckedHistoryQueries" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.
```
I dont understand that error, because there is a method called `discardCheckedHistoryQueries`, also its working for the saved queries.
Could you help with that, did i miss something ?!

2020-08-30 00:29 UTC, rathboma commented
Sure I'll take a look. @ghstng can you do a ui review?

2020-09-01 19:16 UTC, ghstng commented
I can pull into a branch and cleanup, if you both are good with everything.

2020-09-01 19:20 UTC, UtechtDustin commented
Its fine for me, im not a UI expert :-)

2020-09-01 19:35 UTC, rathboma commented
Sure then I can fix the vue problem

2020-09-01 19:37 UTC, UtechtDustin commented
> Sure then I can fix the vue problem

Thanks, please then tell me what was the issue was :-)

2020-09-02 02:11 UTC, rathboma commented
@UtechtDustin Your bug is that `discardCheckedHistoryQueries` is outside of the `methods {}` block, simply move it inside `methods`, and it will work (also do that for the other function you added)

2020-09-02 07:24 UTC, UtechtDustin commented
> @UtechtDustin Your bug is that `discardCheckedHistoryQueries` is outside of the `methods {}` block, simply move it inside `methods`, and it will work (also do that for the other function you added)

Oh... How i can't saw that.. Sometimes the small issues are the hardest one..

2020-09-03 22:43 UTC, rathboma commented
If you fix that little bug we'll merge it and do a style tidy up 👍

2020-09-03 22:46 UTC, rathboma requested changes
minor change - do an `await` wherever you can

2020-09-03 22:46 UTC, rathboma commented on src/components/sidebar/core/FavoriteList.vue
> +          this.remove(favorite)
Should you have an `await` here? You will need to do a for() loop to do that

2020-09-03 22:46 UTC, rathboma commented on src/components/sidebar/core/HistoryList.vue
> +        this.remove(historyQuery)
same deal with `await` here

2020-09-04 08:18 UTC, UtechtDustin commented
Lets wait for @ghstng for the design then i will look at this :-)

2020-09-04 13:48 UTC, rathboma commented
We chatted -- the ux is mostly good, we're just going to tweak a few things after it's merged -- it's hard to do that with someone else's branch

2020-09-04 14:13 UTC, UtechtDustin commented
Oh okay, i pushed a new version of that.
Currently i have one last problem (except from the design), if i remove saved query somehow ALL queries will be removed from the list but no one will be removed from the store.
I try to figure out what the problem is, but if you have time it would great if you also could look.

2020-09-04 14:17 UTC, UtechtDustin commented
@rathboma its ready for merge

2020-09-04 16:01 UTC, merged