Bug/connection passwords being saved without encryption
beekeeper-studio/beekeeper-studio pull request #322
Opened 2020-09-07 20:06 UTC by geovannimp

2020-09-07 21:09 UTC, rathboma requested changes
I'm still actually not sure if it's worth encrypting this stuff or just treating the user environment as trusted, but let's go with my original intent!

Good find here with your typescript changes!

I've added a few comments based on the unfortunate limitations of sqlite.

2020-09-07 21:09 UTC, rathboma commented on src/migration/20200907-add_encrypted-columns.js
> +      await runner.startTransaction()
this might not work (rollback correctly) because sqlite cannot remove columns? Not sure.

2020-09-07 21:09 UTC, rathboma commented on src/migration/20200907-add_encrypted-columns.js
> +      await runner.startTransaction()
I think it's best to break this out into two migrations:
1. Create new columns
2. run the update queries (with transaction)

2020-09-08 14:05 UTC, geovannimp commented on src/migration/20200907-add_encrypted-columns.js
> +      await runner.dropColumns('saved_connection', temp_columns)
I can test it again, but I'm almost sure that the columns were dropped.

I tested here again and the columns were dropped. Typeorm must have some tricks to remove the columns.

2020-09-08 14:15 UTC, geovannimp commented
@rathboma I looked at de migration again and we don't really need a temp collumn. Take a look at the migration again, it's a lot simpler now

2020-09-08 14:22 UTC, rathboma commented
Nice

2020-09-08 18:02 UTC, rathboma commented on src/migration/20200907-add_encrypted-columns.js
> +      SavedConnection.save(entities);
I think you need an `await` here!

2020-09-08 23:58 UTC, geovannimp commented on src/migration/20200907-add_encrypted-columns.js
> +      SavedConnection.save(entities);
Yeap, fixed! :D

2020-09-10 14:22 UTC, rathboma commented
tested. Works great. Legend

2020-09-10 14:22 UTC, merged