sidebar-toggling, hotkey
beekeeper-studio/beekeeper-studio pull request #569
Opened 2021-02-19 23:24 UTC by ghstng

2021-02-20 01:37 UTC, rathboma requested changes
One minor thing - moving the keymap to `data`.

2021-02-20 01:37 UTC, rathboma commented on src/components/CoreInterface.vue
> +      keymap() {
This should be in `data`

2021-02-20 01:37 UTC, rathboma commented on src/components/sidebar/CoreSidebar.vue
> +      v-on="$listeners"
Nice, I've never used this, cool.

2021-02-22 16:59 UTC, rathboma commented
One thing we've forgotten:

Adding a menubar entry for this under `view`. I should be able to do that before we merge.

2021-02-24 02:09 UTC, rathboma commented
@ghstng it is now not possible to resize the sidebar at all.

2021-02-24 02:11 UTC, rathboma commented
![image](https://user-images.githubusercontent.com/279769/108935403-417b7c00-7613-11eb-8c3d-06302936f899.png)

If you make the window smaller

2021-02-24 02:12 UTC, rathboma requested changes
Problems:

1. Can't resize the sidebar at all
2. It seems to start really wide
3. Make a small window and it squishes into the side

2021-02-24 02:14 UTC, rathboma commented
I'm unfortunately going to undo your keymap too -- ctrl+b breaks standard mac and ubuntu keyboard shortcuts when editing (that's back a character in emacs-land, which both OSes bind to)

2021-03-02 18:01 UTC, ghstng commented
@rathboma rgr will look.

2021-03-03 23:10 UTC, merged