Persisted sorting for the connection list
beekeeper-studio/beekeeper-studio pull request #782
Opened 2021-08-28 21:28 UTC by nmelnick

This PR is to address issue #372 .

I'm new to Vue and this project, so this PR is open to feedback, and if there is ongoing work that replaces this, I'm happy to let it go, too.

The default sort order for the connection list is by ID, which kinda correlates to when it was created. This becomes unwieldy over time. This PR adds a new button to change sort order, and persists the sort order in settings on each change. I added to the initial list of sort options in the issue, providing:

* Color (labelColor)
* Created (id)
* Name (name)
* Connection type/protocol (type)

2021-09-08 15:04 UTC, nmelnick commented
I see you were busy! Congratulations on 2.0, @rathboma! :)

I have merged in the latest changes from master and tested.

2021-09-13 21:02 UTC, rathboma requested changes
one minor change, one higher order question

2021-09-13 21:02 UTC, rathboma commented on apps/studio/src/migration/20210811_add_sort_to_settings.js
> +        ('sortOrder', 'id', '0')
could we call this `connectionSortOrder` rather than `sortOrder`? That way we can have a different sort order for other stuff.

2021-09-13 21:02 UTC, rathboma commented on apps/studio/src/store/modules/settings/SettingStoreModule.ts
> +    sortOrder(state) {
I think this adds much needed functionality. But it does mean that connections cannot be dragged / dropped for sorting. Do you think that's a good trade off?

2021-09-14 18:47 UTC, rathboma commented
Know what? I think this is good enough to merge.

2021-09-14 18:47 UTC, merged

2021-09-14 19:06 UTC, nmelnick commented
@rathboma Hah -- sorry, didn't get to those notifications in time! I'll do a follow up PR taking your comments into account, I think they're all good. I think allowing a 'manual' sort order makes a ton of sense, I was just blinded to it because I didn't use it.

2021-09-14 20:37 UTC, rathboma commented
It's all good! I think this is very useful as-is. Don't worry about the manual sorting, we'll be adding folders soon so that will require some changes anyway.